"""Adding new fields for signature

Revision ID: 46908decd287
Revises: 6cc777e5e9b5
Create Date: 2026-03-15 11:00:43.253380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46908decd287'
down_revision = '6cc777e5e9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan_type')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
